### ISSUE TITLE
How can I use django-formset with django-crispy-forms?

### ISSUE THREAD

**Issue by AhmedSalam22** [jrief/django-formset#8]
How can I use django-formset with django-crispy-forms?
is there is a way to replace {% render_form %} tage with {% crispy%} and
if i used  {% crispy%}  instead of {% render_form %}  will cause any problem?

**Comment by jrief** [comment]
I never tested this and I don't see any benefit doing this. Why are you asking, what would you like to do?

**Comment by AhmedSalam22** [comment]
I have already Django project that use django-crispy-forms and i just want to replace select options with the feature you has in django-formset

I just want to use  Selectize, UploadedFileInput widgets 

![Screenshot (827)](https://user-images.githubusercontent.com/35177448/175503006-29c8a73b-03da-41e1-95f2-bad395124638.png)

**Comment by AhmedSalam22** [comment]
I can use vanilla JavaScript to handle validation with simple code but you has awesome feature Selectize, UploadedFileInput widgets

i just want to  integrate this feature into my current project
![image](https://user-images.githubusercontent.com/35177448/175505257-b0035fc8-4ae9-4a0b-834c-b276bb71785d.png)

**Comment by jrief** [comment]
I don't know Crispy-Forms enough to handle that. However, if Crispy-Forms has features django-formset doesn't, please let me know, so that I can have a look at them. What I see from your screenshots are tabular inlines. The same effect can be achieved in django-formset using CSS styling.

> but you has awesome feature Selectize, UploadedFileInput widgets

and there are more features to come:
- sortable DualSelector
- sortable Collections (counterpart of Inlines)
- widget for a Rich-Text-Editor (supporting image uploads)
- editor for GeoSpacials, incl. Points, Lines, Polygons, MultiPolygons

**Comment by MansourHaghgoo** [comment]
please help me. how to use FormCollection in CreateView ?
